version: "3.7"
services:
  webapi:
    build: ./springboot
    container_name: spring-webapi
    restart: always
    ports:
      - "8081:8080"
    # depends_on:
    #   - db
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
  # db:
  #   image: mysql:8.0.16
  #   container_name: asakatu-kun-db
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: asakatu
  #     MYSQL_USER: asakatu
  #     MYSQL_PASSWORD: himitu
  #   volumes:
  #     - ./mysql/sqls:/docker-entrypoint-initdb.d
  #   ports:
  #     - "3306:3306"
